language: python
#python:
#  - 2.7
#  - 3.3
#  - 3.4
#  - 3.5
#  - 3.6-dev

matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      language: generic
      python: 3.5

cache: pip

addons:
  apt:
    packages:
      - r-base
      - clang-3.4
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise

before_install:
  - python3
  - which python3
  - which python
  - false
  - >
    if [[ $TRAVIS_OS_NAME == osx ]]; then
      sudo ln -sf $(which python3) $(which python)
      sudo ln -sf $(which pip3) $(which pip)
      TRAVIS_PYTHON_VERSION=3.5

      brew tap caskroom/cask
      brew tap homebrew/science
      brew cask install julia
      brew install r
    else
      sudo add-apt-repository -y ppa:staticfloat/juliareleases
      sudo apt-get update
      sudo apt-get install julia
      # https://github.com/coala/coala/issues/3184
      pip install -U py==1.4.29 pip
    fi

  - export TRAVIS_PYTHON_VERSION_MAJOR=${TRAVIS_PYTHON_VERSION%.[0-9]}
  - export TRAVIS_PYTHON_VERSION_MINOR=${TRAVIS_PYTHON_VERSION#[0-9].}

  # https://github.com/coala/coala/issues/3183
  - cat test-requirements.txt docs-requirements.txt >> requirements.txt
  # OSX sed -i does not mean the same as Linux sed -i
  - >
    sed -e '/^-r/d' requirements.txt > requirements.new
    mv requirements.new requirements.txt
  # OSX is not a real Travis 'python' image, so it does not install
  # requirements.txt automatically.
  - >
    if [[ $TRAVIS_OS_NAME == osx ]]; then
      pip install -r requirements.txt
    fi

before_script:
  - julia -e 'Pkg.add("Lint")'

script:
  - >
    if [[ $TRAVIS_PYTHON_VERSION_MINOR < 4 || $TRAVIS_PYTHON_VERSION_MAJOR == 2 ]]; then
      coverage run setup.py install | grep -q 'coala supports only python 3.4 or later'
    else
      bash .misc/tests.sh
      python setup.py install
      pip install coala-bears --pre -U
      # https://github.com/coala/coala-bears/issues/1037
      if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
        python3 -m nltk.downloader punkt maxent_treebank_pos_tagger averaged_perceptron_tagger
      else
        sed -i '/bears = GitCommitBear/d' .coafile
      fi
      coala --non-interactive
      make -C docs clean
      python setup.py docs
    fi
  - bash .misc/deploy.coverage.sh

notifications:
  email: false
