sudo: false
language: python
python:
  - 3.4

.matrix:
  include:
    # OSX build removed due to long build startup delays
    # Restore matrix job entry from d2d67fab to test OSX
    - python: 2.7
      env: UNSUPPORTED=true
      script: .misc/check_unsupported.sh
    - python: 3.3
      env: UNSUPPORTED=true
      script: .misc/check_unsupported.sh

cache:
  pip: true
  directories:
    - node_modules
    - docs/_build

.addons:
  apt:
    packages:
      - clang-3.4
    sources:
      - llvm-toolchain-precise

services:
  - docker

.before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then TRAVIS_PYTHON_VERSION=3.5; fi

  - >
    if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew install python3
      sudo ln -sf $(which python3) $(which python)
      sudo ln -sf $(which pip3) $(which pip 2>/dev/null || echo /usr/bin/pip)
    fi

  # Use pip 9, so that setuptools can be downgraded.
  - pip install pip==9 setuptools==17
  - python .misc/check_setuptools.py

  # https://github.com/coala/coala/issues/3183
  # Travis automatically installs the `requirements.txt` in "install" stage
  - cp requirements.txt requirements.orig
  - cat test-requirements.txt docs-requirements.txt >> requirements.txt
  - sed -i.bak '/^-r/d' requirements.txt

  # OSX is not a real Travis 'python' image, so it does not install
  # requirements.txt automatically.
  - if [[ $TRAVIS_OS_NAME == osx ]]; then pip install -r requirements.txt; fi

  # For bears in .coafile requiring npm dependencies
  - npm install

.before_script:
  # Restore the original requirements.txt
  - mv requirements.orig requirements.txt
  - python .misc/check_setuptools.py

script:
  - >
    docker run --volume=$(pwd):/coala coala/base:pre /bin/sh -c "
        set -e -x
        pip3 install -U /coala/;
        cd /coala-bears;
        git pull;
        python3 setup.py install;
        rm bears/Constants.py;  # There are no tests covering this module
        rm bears/c_languages/CSharpLintBear.py tests/c_languages/CSharpLintBearTest.py;
        rm bears/java/InferBear.py tests/java/InferBearTest.py;
        rm bears/haskell/GhcModBear.py tests/haskell/GhcModBearTest.py;
        rm -r bears/verilog tests/verilog/;
        export OS_NAME=posix;
        python3 -m pytest --cov --cov-fail-under=100;
      "

notifications:
  email: false

branches:
  exclude:
    - /^sils\//
