language: python
python:
  - 3.4

install:
  - pip install -U py==1.4.29
  - pip install -r requirements.txt -r test-requirements.txt
  - pip install -r docs-requirements.txt

script:
  - bash .misc/tests.sh

notifications:
  email: false
