environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.misc\\run_with_env.cmd"
    PIP_CACHE_DIR: C:\pip_cache

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

cache:
  - "C:\\pip_cache"

branches:
  except:
    - /^sils\/.*/

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PATH=%PATH%;C:\\Program\ Files\\Git\\mingw64\\bin"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "%CMD_IN_ENV% python -m pip install setuptools==21"
  - "%CMD_IN_ENV% python .misc/check_setuptools.py"
  - 'if %PYTHON_VERSION% != "2.7" (%CMD_IN_ENV% python -m pip install -r requirements.txt -r test-requirements.txt)'

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - 'if %PYTHON_VERSION% != "2.7" (CMD_IN_ENV% py.test)'
  - 'if %PYTHON_VERSION% != "2.7" (%CMD_IN_ENV% python setup.py install)'

on_success:
  - codecov

on_failure:
  - codecov

matrix:
  fast_finish: true
